import { User } from './user';

export const USERS : User[] = [
    { id : 1, name : "Aldo Chocos", username : 'achocos', phone : '995742639', email: 'aldo.chocos@pucp.pe', website : ''  },
    { id : 2, name : "Luis Chocos", username : 'lchocos', phone : '991234567', email: 'luis.chocos@pucp.pe', website : '' },
    { id : 3, name : "Martín Chocos", username : 'mchocos', phone : '987654321', email: 'martin.chocos@pucp.pe', website : '' },
    { id : 4, name : "David Chocos", username : 'dchocos', phone : '998747874', email: 'david.chocos@pucp.pe', website : ''  },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 6, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 7, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 8, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 9, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 10, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 11, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 12, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 13, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 14, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 15, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 16, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 17, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 18, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 19, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 20, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 21, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 22, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 23, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 24, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
    { id : 5, name : "Nora Evangelista", username : 'nevangelista', phone : '992589974', email: 'nora.evangelista@pucp.pe', website : '' },
];
    
